### ISSUE TITLE
AspnetCore: EntitySet not found for type...Sequence contains no matching element

### ISSUE THREAD

**Issue by randellhodges** [Breeze/breeze.server.net#52]
I am attempting to implement something similar, but simpler, to NorthWind DTO example under the breeze.js.samples repo.

I can add and update my EF entities by way of my DTO objects without error. If I delete one however, I get the error.

```
System.ArgumentException: EntitySet not found for type MyApp.Web.Models.Tile ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Breeze.Persistence.EF6.EFPersistenceManager`1.GetEntitySetName(Type entityType)
   at Breeze.Persistence.EF6.EFPersistenceManager`1.GetKeyValues(Object entity)
   --- End of inner exception stack trace ---
   at Breeze.Persistence.EF6.EFPersistenceManager`1.GetKeyValues(Object entity)
   at Breeze.Persistence.EF6.EFPersistenceManager`1.GetKeyValues(EntityInfo entityInfo)
   at Breeze.Persistence.SaveWorkState.<ToSaveResult>b__20_5(EntityInfo entityInfo)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Breeze.Persistence.SaveWorkState.ToSaveResult()
   at Breeze.Persistence.PersistenceManager.SaveChanges(JObject saveBundle, TransactionSettings transactionSettings)
   at MyApp.Web.Controllers.ProfileController.SaveChanges(JObject req)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
```

I am hooking into BeforeSaveEntities and AfterSaveEntities and using Automapper. I can see the Sql generated executes fine. It has something to do with turning the response into valid response for SaveChanges.

Not sure why an insert and update would function, but a delete wouldn't.

```
public SaveResult SaveChanges([FromBody]JObject req)
{
	if (UserID != null)
	{
		_manager.BeforeSaveEntitiesDelegate += BeforeSaveEntities;
		_manager.AfterSaveEntitiesDelegate += AfterSaveEntities;

		var results = _manager.SaveChanges(req);
		return results;
	}

	return null;
}
		
private static readonly List<(Type ClientType, Type ServerType)> _dtoMap = new List<(Type, Type)>
{
	( typeof(Web.Models.Tile), typeof(Data.Models.Tile) )
};


private Dictionary<Type, List<EntityInfo>> BeforeSaveEntities(Dictionary<Type, List<EntityInfo>> saveMap)
{         
	foreach (var item in _dtoMap)
	{
		if (saveMap.TryGetValue(item.ClientType, out List<EntityInfo> clientGroup))
		{
			// We don't persist client entities
			saveMap.Remove(item.ClientType);

			if (saveMap.TryGetValue(item.ServerType, out List<EntityInfo> serverGroup) == false)
				saveMap[item.ServerType] = serverGroup = new List<EntityInfo>();

			foreach (var clientEntityInfo in clientGroup)
			{
				var serverEntity = _mapper.Map(clientEntityInfo.Entity, item.ClientType, item.ServerType);
				var serverEntityInfo = _manager.CreateEntityInfo(serverEntity, clientEntityInfo.EntityState);
				
				if (clientEntityInfo.AutoGeneratedKey != null)
				{
					// Potential optmization: Cache this somewhere, or define it, or even create some sort of interface
					// on the client dto. I was thinking cache so we don't dirty up the dto...more.
					var map = _mapper.ConfigurationProvider.FindTypeMapFor(item.ClientType, item.ServerType);
					var prop = map.GetPropertyMaps().First(pm => pm.SourceMember == item.ClientType.GetProperty(clientEntityInfo.AutoGeneratedKey.PropertyName));

					clientEntityInfo.AutoGeneratedKey.PropertyName = prop.DestinationProperty.Name;
					clientEntityInfo.AutoGeneratedKey.Entity = serverEntity;
				}

				serverEntityInfo.UnmappedValuesMap = clientEntityInfo.UnmappedValuesMap;
				serverEntityInfo.OriginalValuesMap = clientEntityInfo.OriginalValuesMap;
				serverEntityInfo.AutoGeneratedKey = clientEntityInfo.AutoGeneratedKey;
				serverEntityInfo.ForceUpdate = clientEntityInfo.ForceUpdate;

				serverGroup.Add(serverEntityInfo);
			}
		}
	}

	return saveMap;
}

private void AfterSaveEntities(Dictionary<Type, List<EntityInfo>> saveMap, List<KeyMapping> keyMappings)
{
	foreach (var item in _dtoMap)
	{
		if (saveMap.TryGetValue(item.ServerType, out List<EntityInfo> serverGroup))
		{
			// We don't persist client entities
			saveMap.Remove(item.ServerType);

			if (saveMap.TryGetValue(item.ClientType, out List<EntityInfo> clientGroup) == false)
				saveMap[item.ClientType] = clientGroup = new List<EntityInfo>();

			foreach (var serverEntityInfo in serverGroup)
			{
				var clientEntity = _mapper.Map(serverEntityInfo.Entity, item.ServerType, item.ClientType);
				var clientEntityInfo = _manager.CreateEntityInfo(clientEntity, serverEntityInfo.EntityState);

				clientEntityInfo.UnmappedValuesMap = serverEntityInfo.UnmappedValuesMap;
				clientEntityInfo.OriginalValuesMap = serverEntityInfo.OriginalValuesMap;
				clientEntityInfo.AutoGeneratedKey = serverEntityInfo.AutoGeneratedKey;
				clientEntityInfo.ForceUpdate = serverEntityInfo.ForceUpdate;

				clientGroup.Add(clientEntityInfo);
			}

			// Update the key mappings. Used when new items are created.
			var serverName = item.ServerType.FullName;
			var clientName = item.ClientType.FullName;

			keyMappings.ForEach(keyMapping =>
			{
				if (keyMapping.EntityTypeName == serverName)
					keyMapping.EntityTypeName = clientName;
			});
		}
	}
}
```

This happens anytime there is a delete. It could be by itself or it could come along with other changes. Either way, I always get that error.

I am using the EF as a designer for my metadata. Maybe something isn't right there? Still, not sure why that would only affect deletes.

**Comment by randellhodges** [comment]
I downloaded the source and compiled so I could step thru it. It is generated inside PersistenceManager.cs. In the ToSaveResult call

```
        var deletes = SaveMap.SelectMany(kvp => kvp.Value.Where(ei => (ei.EntityState == EntityState.Deleted || ei.EntityState == EntityState.Detached))
          .Select(entityInfo => new EntityKey(entityInfo.Entity, ContextProvider.GetKeyValues(entityInfo)))).ToList();
```

this ends up calling GetEntitySetName inside EFPersistenceManager.cs, but this time, the type that is passed along is my DTO.

```
    public String GetEntitySetName(Type entityType) {
      var metaWs = ObjectContext.MetadataWorkspace;
      EntityType cspaceEntityType;
      var ospaceEntityTypes = metaWs.GetItems<EntityType>(DataSpace.OSpace);
      if (ospaceEntityTypes.Any()) {
        var ospaceEntityType = ospaceEntityTypes.First(oet => oet.FullName == entityType.FullName);
        cspaceEntityType = (EntityType)metaWs.GetEdmSpaceType(ospaceEntityType);
      } else {
        // Old EDMX ObjectContext has empty OSpace, so we get cspaceEntityType directly
        var cspaceEntityTypes = metaWs.GetItems<EntityType>(DataSpace.CSpace);
        cspaceEntityType = cspaceEntityTypes.First(et => et.FullName == entityType.FullName);
      }
```

The type that is going into it is my DTO, but the types inside the metaWs is the EF model types. Because of this, the .First call doesn't find anything and throws an error.

**Comment by SeanEG** [comment]
Hi there!

Is there any more information on this problem/potential fix? I am currently experiencing the same thing (add and update with DTOs just fine, but deleting causes the exception outlined above).

Are there perhaps any known workarounds?

Thanks.

**Comment by randellhodges** [comment]
I decided against using this because the support seemed lacking.

I think what I tried before abandoning this framework was to get the source
and to revert the changes I made money in my previous post and then map
things.

Not sure if that'll fix it for you or not. It has been a while since I
looked at this.

**Comment by steveschmitt** [comment]
Have you tried the latest versions?  They are on nuget now:

https://www.nuget.org/packages/Breeze.Core/
https://www.nuget.org/packages/Breeze.Persistence/
https://www.nuget.org/packages/Breeze.AspNetCore.NetCore/
https://www.nuget.org/packages/Breeze.Persistence.EFCore/
https://www.nuget.org/packages/Breeze.Persistence.EF6/

**Comment by SeanEG** [comment]
Hey guys, thanks for the replies!

Steve, unfortunately updating to the latest version didn't solve the issue. I believe that Randell is correct in his conclusion of where the issue lies. This particular file doesn't appear to have been updated recently. Regardless, I still updated breeze, but it was a no-go, unfortunately.

I seem to have a work around going (albeit a messy one), which is probably similar to what Randell came up with as well.

After the save has taken place, and the dtos have already been converted to models in beforeSave, and back to dtos in the afterSave. What I do am doing is, I then convert the dtos *back* into models before ToSaveResult() is called, and finally convert the deletedkeys and entities of the SaveResult on the server to what the client expects (ie. updateing the entitiyTypeName in SaveResult.Deletedkeys and converting the models back into dtos in SaveResult.Entities).

After some initial testing, it seems to be working, but I'm not sure how maintainability this will be in the long run.

Any chance that this bug could get a deeper look?
