### ISSUE TITLE
Error Generating Metadata with EF Core and Identity

### ISSUE THREAD

**Issue by jcsilvers** [Breeze/breeze.server.net#76]
When I attempt to generate metadata I get the below error. I am using EF Core with identity

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Breeze.Persistence.EFCore.MetadataBuilder.BuildAssocName(INavigation prop) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 138
   at Breeze.Persistence.EFCore.MetadataBuilder.CreateNavProperty(INavigation p) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 128
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Breeze.Persistence.EFCore.MetadataBuilder.CreateMetaType(IEntityType et, Dictionary`2 dbSetMap) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 89
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Breeze.Persistence.EFCore.MetadataBuilder.GetMetadataFromContext(DbContext dbContext) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 21
   at Breeze.Persistence.EFCore.EFPersistenceManager`1.BuildJsonMetadata() in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\EFPersistenceManager.cs:line 109
   at Breeze.Persistence.PersistenceManager.Metadata() in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence\PersistenceManager.cs:line 34
   at MITSBusinessLib.Repositories.EventOrganizerRepo.MetaData() in C:\Users\Jason\Documents\MITSWebApp\MITSBusinessLib\Repositories\EventOrganizerRepo.cs:line 28
   at MITSWebServices.Controllers.EventOrganizerController.Metadata() in C:\Users\Jason\Documents\MITSWebApp\MITSWebServices\Controllers\EventOrganizerController.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

This is my Context

```C#
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using MITSDataLib.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace MITSDataLib.Contexts
{
    public class MITSContext : IdentityDbContext<User>
    {

        public MITSContext(DbContextOptions<MITSContext> options): base(options)
        {
            //Do I need these with EF CORE?
            //Configuration.ProxyCreationEnabled = false;
            //Configuration.LazyLoadingEnabled = false;
        }
                
        public DbSet<WildApricotEvent> WaEvents { get; set; }
        public DbSet<WildApricotRegistrationType> WaRegistrationTypes { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Speaker> Speakers { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<Person> People { get; set; }

        
    }
}
```

**Comment by jcsilvers** [comment]
I don't think it is an issue with Identity. When I debug with the breeze libraries the context is null.  I tried creating a Metadata only context provider and it is giving me the same error. 

```C#
using Microsoft.EntityFrameworkCore;
using MITSDataLib.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace MITSDataLib.Contexts
{
    public class MITSMetadata : DbContext
    {
        public MITSMetadata(DbContextOptions<MITSMetadata> options): base(options)
        {
            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

        }

        public DbSet<Tag> Tags { get; set; }
        public DbSet<Speaker> Speakers { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<Person> People { get; set; }
    }
}

```

**Comment by bnemetchek** [comment]
There is a bug in MetadataBuilder.cs that will spit out this error when the EF nav inverse properties are not entirely set up correctly.  If you download the source and temporarily use it in your project, you can debug and see the error.

Below is a modification to the offending function in MetadataBuilder.cs that will better show the error:

````
private MetaNavProperty CreateNavProperty(INavigation p) {
      var np = new MetaNavProperty();
      np.NameOnServer = p.Name;
      np.EntityTypeName = NormalizeTypeName(p.GetTargetType().ClrType);
      np.IsScalar = !p.IsCollection();
      // FK_<dependent type name>_<principal type name>_<foreign key property name>
      np.AssociationName = BuildAssocName(p);
      if (p.IsDependentToPrincipal()) {
        np.AssociationName = BuildAssocName(p);
        np.ForeignKeyNamesOnServer = p.ForeignKey.Properties.Select(fkp => fkp.Name).ToList();
      } else {
                try
                {
                    np.AssociationName = BuildAssocName(p.FindInverse());
                    np.InvForeignKeyNamesOnServer = p.ForeignKey.Properties.Select(fkp => fkp.Name).ToList();
                }
                catch (Exception ex)
                {
                    var errorText = "Missing: " + p.DeclaringEntityType.Name + p.ForeignKey.DeclaringEntityType.Name;
                    Console.WriteLine(errorText);
                    ////var code = $"modelBuilder.Entity<{p.ForeignKey.DeclaringEntityType.Name}>().HasOne(x => x.FrontImage).WithMany(x => x.{p.DeclaringEntityType.Name});";
                    //var code = p.ForeignKey.ToString();
                    //Console.WriteLine(code);
                    //throw ex;
                    throw new Exception(errorText);
                }
      }

      return np;
    }
````

**Comment by jtraband** [comment]
So not sure I understand this.  Is there a bug in the breeze MetadataBuilder or is it simply that it doesn't handle an error cleanly in the case where EF nav properties are not set up properly ( a smaller bug) ?  

I wrote this lib but haven't looked at it lately, and am just now getting back to updating it.  So any additional info would be great.

**Comment by bnemetchek** [comment]
It's not exactly a bug but it doesn't fully describe to the user when there is no inverse for a nav property.  It would be more helpful to tell the user the name of the entity and nav property rather than just give a null error when p.FindInverse() is null.

Also, If you're looking at updating the code to handle EF 2.1 and/or 2.2, I've completed this task and am trying to put together a PR.  In the PR, I completely rewritten the metadata routine so that it is more like the EF6 metadata rather than the new format.  The PR isn't completely tested, but it works in the limited testing I've done.  Also, it's using the new OData functionality rather than JSON.  Let me know if they could be of use to you.

**Comment by jcsilvers** [comment]
Would it help if I posted a repo duplicating the issue? 

I agree with @bnemetchek if it is an error in the models it would be helpful to know where breeze is having an issue because EF Core isn't throwing any errors

**Comment by jtraband** [comment]
Yes, a simple repo would be great.

**Comment by jtraband** [comment]
@bnemetchek We deliberately avoided OData this time around because it seemed like Microsoft had deprecated its support.  And also because we can extend the JSON metadata but this is cumbersome with OData.  I will be spending some time looking into this and could be convinced otherwise but I do agree that upgrading the lib to work with EF 2.2 makes a lot of sense.  I will likely be working on this within the next few weeks.  and... thanks for looking into the issue.

**Comment by bnemetchek** [comment]
I've created this PR that will enable EF 2.2/OData with a short explanation:

https://github.com/Breeze/breeze.server.net/pull/77

**Comment by jcsilvers** [comment]
I rebuilt everything from scratch and I couldn't replicate the error I was getting..... everything seems to be working just fine now.

Anyway...... if anyone is looking for a repo that has .net core 2.1 Breeze, Identity and Openiddict Oauth server using the password grant type. Here you go.

https://github.com/jcsilvers/breezenetcore21
